name: safe_drive
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  app_links: ^6.4.1
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  firebase_analytics: ^12.0.4
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  flutter_localization: ^0.3.3
  pull_to_refresh: ^2.0.0
  package_info_plus: ^9.0.0
  get: ^4.6.6
  envied: ^1.1.1

  # Flavor
  flutter_flavorizr: ^2.4.1

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.5

  # UI
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.3.2
  shimmer: ^3.0.0

  # Signature
  fast_rsa: ^3.8.6

  # Logger
  amplitude_flutter: ^4.3.9

  # Network
  dio: ^5.9.0
  connectivity_plus: ^6.0.5

  # Auth
  supabase_flutter: ^2.8.0
  google_sign_in:
    ^7.2.0

    # Media
  image_picker: ^1.2.1
  image_cropper: ^11.0.0

  # Permissions
  permission_handler: ^11.3.1

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^1.1.1

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
