name: safe_drive
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  app_links: ^6.4.0
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  firebase_analytics: ^11.3.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.3
  flutter_localization: ^0.3.3
  pull_to_refresh: ^2.0.0
  package_info_plus: ^8.3.0
  get: ^4.6.6
  envied: ^1.1.1

  # Flavor
  flutter_flavorizr: ^2.2.3

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.5

  # UI
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.0
  shimmer: ^3.0.0

  # Signature
  fast_rsa: ^3.6.6

  # Logger
  sentry_flutter: ^8.13.2
  amplitude_flutter: ^4.3.2

  # Auth
  supabase_flutter: ^2.8.0
  google_sign_in: ^6.2.2

  venturo_api_manager: ^1.0.1
  vpack: ^1.0.0
  image_picker: ^1.2.1
  image_cropper: ^11.0.0

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^1.1.1

  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
